name: Build and test fragments

on:
  push:
      paths: ["fragments/**"]

jobs:
  setup:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v1
        with:
            path: fragments/port-animation-react/node_modules
            key: node_modules-${{ hashFiles('fragments/port-animation-react/package-lock.json') }}
            # loading an older version is fine here, since it will get an npm install
            restore-keys: |
                node_modules-

      - name: Install dependencies
        run: |
          cd fragments/port-animation-react
          npm ci

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load node_modules
        uses: actions/cache@v1
        with:
          path: fragments/port-animation-react/node_modules
          key: node_modules-${{ hashFiles('fragments/port-animation-react/package-lock.json') }}

      - name: Build frontend package
        run: |
          cd fragments/port-animation-react
          npm run build

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Load node_modules
          uses: actions/cache@v1
          with:
              path: fragments/port-animation-react/node_modules
              key: node_modules-${{ hashFiles('fragments/port-animation-react/package-lock.json') }}

        - name: Run eslint
          run: |
              cd fragments/port-animation-react
              npm run lint:prod

  run-port-animation-fragment-unit-tests:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: browser-actions/setup-chrome@latest
        - run: chrome --version

        - name: Load node_modules
          uses: actions/cache@v1
          with:
            path: fragments/port-animation-react/node_modules
            key: node_modules-${{ hashFiles('fragments/port-animation-react/package-lock.json') }}

        - name: Run port-animation fragment unit tests
          run: |
            cd fragments/port-animation-react
            CHROME_BIN=$(which chrome) npm run test
