name: Build an test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      # Runs a set of commands using the runners shell
      - name: Run build of frontend package
        run: |
          npm ci
          npm run build
      - name: Run main app unit tests
        run: |
          cd main-app
          CHROME_BIN=$(which chrome) npm run test
