name: Run e2e tests

on:
  pull_request:
  workflow_run:
    workflows: [ "Build and test main app", "Build and test fragments" ]
    types:
      - completed

jobs:
  build-fe-artifact:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: Cache dist folder
        uses: actions/cache@v1
        with:
            path: dist
            key: dist-${{ hashFiles('package-lock.json') }}
            # loading an older version is fine here, since it will get an npm install
            restore-keys: |
                node_modules-

      - name: Install dependencies and build artifact
        run: |
          npm ci
          npm run build

  install-tests-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: e2e-tests/node_modules
          key: node_modules-${{ hashFiles('e2e-tests/package-lock.json') }}
          # loading an older version is fine here, since it will get an npm install
          restore-keys: |
            node_modules-

      - name: Install dependencies
        run: |
          cd e2e-tests
          npm ci

  run-e2e-tests:
      needs: [install-tests-dependencies, build-fe-artifact]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: browser-actions/setup-chrome@latest
        - run: chrome --version

        - name: Load node_modules
          uses: actions/cache@v1
          with:
            path: e2e-tests/node_modules
            key: node_modules-${{ hashFiles('e2e-tests/package-lock.json') }}

        - name: Load build artifact
          uses: actions/cache@v1
          with:
            path: dist
            key: dist-${{ hashFiles('package-lock.json') }}

        - name: Run port-modelling e2e tests
          run: |
            npm run start
            cd e2e-tests
            npm run test

        - name: Archive e2e test results
          uses: actions/upload-artifact@v3
          with:
            name: e2e-test-results
            path: e2e-tests/dist
